### ISSUE TITLE
init script failed adding users (add-user script is missing)

### ISSUE THREAD

**Issue by ibenmiller** [jbossdemocentral/bpms-install-demo#26] opened 2018-01-02 20:27 UTC
Env: Windows 7, Java 8, EAP v7 (also tried v6.4)

Issue: init script is presently failing on adding users  (add-user.ps1 is missing)

**Comment by DuncanDoyle** [comment] 2018-03-08 00:32
This is really strange. I just tried this on my Windows 10 VM, and I can clearly see the "add-user.ps1" file in the ".\target\jboss-eap-7.0\bin" directory. 

My machine is Windows 10 in VirtualBox, Java 8 (161), EAP v7.

Since I can't reproduce, can you verify that this is still an issue?

**Comment by DuncanDoyle** [comment] 2018-03-08 08:55
I've been able to reproduce this. The problem is that PowerShell 2.0 seems to be unable to delete paths longer than 260 characters (why Windows? Why? This has been a problem for over 15 years!!!). In PowerShell 6, I had  a workaround for the RemoveItem command, but that does not work in PowerShell v2.0. So I need to find some sort of fix to get around that problem.

What happens is that the EAP directory is only partially deleted (e.g. that add-user.ps1 script is gone), but the installer thinks EAP is already there, so it doesn't do anything, which leaves a half-broken installation.

Again, root cause: Windows 260 character path limit.

**Comment by DuncanDoyle** [comment] 2018-03-08 09:22
OK, the previous analysis is wrong. The problem is that PowerShell v2.0 happily continues executing it scripts while the EAP installer is still running ... So this screws up the installation process. This does not seem to happen in later version of PowerShell.

**Comment by DuncanDoyle** [comment] 2018-03-08 11:02
I'm not really a Windows guy, but I've got a question. Would it be possible for you to use PowerShell v3, because none of the issues I have with PowerShell v2 are present in v3. Also, given that PowerShell v3 seems to have been released in 2012 and has a Windows 7 version, it seems reasonable to simply upgrade to PowerShell v3 instead of trying to hack around various issues in the installer scripts ... 

WDYT?

**Comment by ibenmiller** [comment] 2018-03-08 15:29
Yes I can. Not sure what I did but got past this shortly after raising the issue. 

On Mar 8, 2018, at 6:02 AM, Duncan Doyle <notifications@github.com> wrote:

I'm not really a Windows guy, but I've got a question. Would it be possible for you to use PowerShell v3, because none of the issues I have with PowerShell v2 are present in v3. Also, given that PowerShell v3 seems to have been released in 2012 and has a Windows 7 version, it seems reasonable to simply upgrade to PowerShell v3 instead of trying to hack around various issues in the installer scripts ...

WDYT?

**Comment by DuncanDoyle** [comment] 2018-03-08 16:30
OK, cool. It really seems to be related to PowerShell v2 which does not respect the "-Wait" setting on the Start-Process function when using our BPM Suite installer. I'll close this issue with the comment that we will not support PowerShell v2 and people need to upgrade to v3.

**Closed as completed by DuncanDoyle** 2018-03-08 16:30 UTC
